### health check
GET http://localhost:8000/catalog-service/health_check

### catalog 전체 조회
GET http://localhost:8000/catalog-service/catalog

### catalog 단건 조회
GET http://localhost:8000/catalog-service/catalog/CATALOG-003
