# Source / Sink 공통

### Connector 조회
GET 127.0.0.1:8083/connectors

### Connector [ my-source-connect ] 상세 조회
GET 127.0.0.1:8083/connectors/my-source-connect/status

### Connector 삭제
DELETE 127.0.0.1:8083/connectors/my-source-connect


### Source Connector 등록
POST 127.0.0.1:8083/connectors
Content-Type: application/json

{
   "name" : "my-source-connect",
   "config" : {
      "connector.class" : "io.confluent.connect.jdbc.JdbcSourceConnector",
      "connection.url":"jdbc:mariadb://localhost:3307/mydb",
      "connection.user":"zhyun",
      "connection.password":"",
      "mode": "incrementing",
      "incrementing.column.name" : "id",
      "table.whitelist":"mydb.users",
      "topic.prefix" : "my_topic_",
      "tasks.max" : "1"
   }
}


### Sink Connector 등록
POST 127.0.0.1:8083/connectors
Content-Type: application/json

{
  "name":"my-sink-connect",
  "config":{
    "connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector",
    "connection.url":"jdbc:mariadb://localhost:3307/mydb",
    "connection.user":"zhyun",
    "connection.password":"",
    "auto.create":"true",
    "auto.evolve":"true",
    "delete.enabled":"false",
    "tasks.max":"1",
    "topics":"my_topic_users"
  }
}
