### health check
GET http://localhost:8000/order-service/health_check

### 회원의 신규 주문 생성
POST http://localhost:8000/order-service/a2af3fe4-804d-491c-8d4c-50ca6583c1ef/orders
Content-Type: application/json

{
  "productId": "CATALOG-003",
  "qty" : 15,
  "unitPrice": 2500
}

### 회원의 주문 내역 조회
GET http://localhost:8000/order-service/a2af3fe4-804d-491c-8d4c-50ca6583c1ef/orders
