### user service - health check
GET localhost:8000/user-service/health_check

### user service - welcome
GET localhost:8000/user-service/welcome

### user service - users
POST localhost:8000/user-service/users
Content-Type: application/json

{
  "email": "zhyun@kim.wlgus",
  "name": "얼거스 김",
  "pwd": "zhyun"
}

