###  health check
#GET 127.0.0.1:8000/user-service/health_check
GET 127.0.0.1:65217/health_check

###  welcome 메세지 출력
GET localhost:8000/user-service/welcome

###  users 등록
#POST 127.0.0.1:8000/user-service/users
POST 127.0.0.1:65217/users
Content-Type: application/json

{
  "email": "zhyun@asd",
  "name": "얼거스 김",
  "pwd": "zhyun"
}

###  users 로그인
POST 127.0.0.1:65217/login
Content-Type: application/json

{
  "email": "zhyun@asd",
  "password": "zhyun"
}

###  users 전체 조회
GET localhost:8000/user-service/users

###  users 단건 조회
GET localhost:8000/user-service/users/22da7089-2939-46cc-b821-2e27339109ca

